"""Audit mask resources without changing source textures or addon configs."""
import csv
import argparse
import json
import math
import re
from pathlib import Path
from PIL import Image

from tool_paths import MOD_ROOT, TOOL_ROOT, WORKSPACE_DIR
ROOT = Path(MOD_ROOT)
WORKSPACES = Path(WORKSPACE_DIR)
REPORT_ROOT = Path(TOOL_ROOT) / 'docs' / 'pbr-mask-audit'


def read_json(path):
    text = path.read_text(encoding='utf-8-sig')
    text = re.sub(r'"(?:\\.|[^"\\])*"|//[^\n]*|/\*[\s\S]*?\*/',
                  lambda m: m[0] if m[0].startswith('"') else '', text)
    return json.loads(re.sub(r',(?=\s*[}\]])', '', text))


def pairs(node):
    if isinstance(node, dict):
        for value in node.values():
            yield from pairs(value)
    elif isinstance(node, list):
        if len(node) == 2 and all(isinstance(x, str) for x in node):
            if node[0].endswith('_color_mask'):
                yield node
        for value in node:
            yield from pairs(value)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--write-index', action='store_true', help='Explicitly update the runtime resource index')
    args = parser.parse_args()
    roots = {ROOT}
    for workspace in WORKSPACES.glob('EP*.code-workspace'):
        for folder in read_json(workspace)['folders']:
            roots.add((workspace.parent / folder['path']).resolve())
    assets, refs, errors = {}, [], []
    for root in sorted(roots):
        for pack in root.glob('resource*'):
            for texture in pack.glob('textures/**/*color_mask*.png'):
                key = texture.relative_to(pack).with_suffix('').as_posix()
                assets.setdefault(key, []).append(texture)
            for config in pack.glob('modconfigs/**/*.json'):
                try:
                    for alias, path in pairs(read_json(config)):
                        refs.append((str(config), alias, path))
                except (ValueError, UnicodeError) as exc:
                    errors.append((str(config), str(exc)))
    # Explicitly named masks need not use the conventional filename suffix.
    packs = [pack for root in roots for pack in root.glob('resource*')]
    for _, _, key in refs:
        if key not in assets:
            found = [pack / (key + '.png') for pack in packs if (pack / (key + '.png')).is_file()]
            if found:
                assets[key] = found
    rows = []
    for key, files in sorted(assets.items()):
        for path in files:
            with Image.open(path) as image:
                pixels = image.convert('RGBA').getdata()
                selected = transparent = opaque = partial = 0
                amin, amax = 255, 0
                for r, g, b, a in pixels:
                    length = math.sqrt(r*r + g*g + b*b)
                    if not length:
                        continue
                    score = max(r, g, b, (r+g)/math.sqrt(2), (r+b)/math.sqrt(2)) / length
                    if score < 0.9999:
                        continue
                    selected += 1
                    transparent += a == 0
                    opaque += a == 255
                    partial += 0 < a < 255
                    amin, amax = min(amin, a), max(amax, a)
                rows.append([str(path), key, image.width, image.height, selected,
                             transparent, opaque, partial, amin if selected else '', amax if selected else ''])
    out = REPORT_ROOT
    out.mkdir(parents=True, exist_ok=True)
    with (out / 'textures.csv').open('w', encoding='utf-8-sig', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(['file', 'texture', 'width', 'height', 'selected_pixels', 'alpha_zero', 'alpha_full', 'alpha_partial', 'alpha_min', 'alpha_max'])
        writer.writerows(rows)
    missing = [ref for ref in refs if ref[2] not in assets]
    # Build-time index only; the game never scans files or images per frame.
    module = ROOT / 'behavior_pack_EP_JXK_0/EpJxkScript/modCommon/pbrMaskResources.py'
    index_text = ('# Generated by tools/audit_pbr_masks.py.\n'
                      + 'AVAILABLE_MASKS = frozenset((\n'
                      + ''.join('    %r,\n' % key for key in sorted(assets)) + '))\n'
                      + 'MISSING_MASKS = frozenset((\n'
                      + ''.join('    %r,\n' % key for key in sorted(set(ref[2] for ref in missing)))
                      + '))\n')
    if args.write_index:
        module.write_text(index_text, encoding='utf-8')
    report = dict(roots=[str(p) for p in sorted(roots)], textures=len(rows), references=len(refs),
                  transparent_rgb_textures=sum(row[5] > 0 for row in rows),
                  fully_metallic_textures=sum(row[4] > 0 and row[4] == row[6] for row in rows),
                  missing_references=missing, parse_errors=errors)
    (out / 'summary.json').write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding='utf-8')
    print(json.dumps({k: v if k not in ('roots', 'missing_references', 'parse_errors') else len(v)
                      for k, v in report.items()}, ensure_ascii=True))


if __name__ == '__main__':
    main()
